from django.db import models

# Create your models here.


# USED FOR TABLE REACTIONS 

# QUERY OF CONVERTING THE PYTHON CODE INTO QUERY BY THIS COMMAND WHICH CAN BE SEEN IN THE MIGRATIONS FLODER=> (PY MANAGE.PY MAKEMIGRATIONS) 
# AND QUERY TO TABLE BY THIS COMMAND => (PY MANAGE.PY MIGRATE)
